notifications:
    email: false

language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
          pip install functools32;
          pip install py2-ipaddress;
          pip install pytz;
      fi
    - pip install doctest-ignore-unicode
    - pip install svgwrite
    - pip install python-coveralls
script: 
    - nosetests
after_success:
    - coveralls
